skinparam classAttributeIconSize 0
package "activity" #DDDDDD {
  class BaseActivity
  class MyDevicesActivity
  class SensorDeviceActivity
  class LightBulbActivity
  class DeviceActivity

}
package "network" #DDDDDD {
  class NetworkManager
}
package "adapter" #DDDDDD {
  class DeviceListAdapter
}
package "model" #DDDDDD {
  class Device
  class LightBulb
  class SensorDevice
  class SensorValues
  class Temperature
  class Pressure
  class Humidity
  class Magnetic
  class Gyroscopic
  class Accelerometer
}

 class NetworkManager{
 +{static} void toggle(Device, boolean, Callback<Response>)
 +{static} void getToggledState(Device, Callback<ToggledStateResponse>)
 +{static} void detectDevices(List<Device>, Callback<DevicesResponse>)
 +{static} void getTemperature(Device, Callback<TemperatureResponse>)
 +{static} void getPressure(Device, Callback<PressureResponse>)
 +{static} void getHumidity(Device, Callback<HumidityResponse>)
 +{static} void getMagnetic(Device, Callback<MagneticResponse>)
 +{static} void getGyroscopic(Device, Callback<GyroscopicResponse>)
 +{static} void getAccelerometer(Device, Callback<AccelerometerResponse>)
 +{static} void getAllSensorValues(Device, Callback<AllSensorValuesResponse>)
 +{static} void getColor(Device, Callback<GetColorResponse>)
 +{static} void setColor(Device, Color, Callback<Response>)
}

abstract class BaseActivity{
}

class DeviceListAdapter {
 +void addDevices(List<Device>)
}

class MyDevicesActivity{
 -void detectDevices()
 -void controlDevice(Device)
}

class SensorDeviceActivity{
 -TextView temperature
 -TextView pressure
 -TextView humidity
 -TextView magnetic
 -TextView gyroscopic
 -TextView accelerometer
 -Switch switch
 -Button getAll
 -Button clearAll
 -void getTemperature()
 -void getPressure()
 -void getHumidity()
 -void getMagnetic()
 -void getGyroscopic()
 -void getAccelerometer()
 -void getAll()
 -void clearAll()
}

class LightBulbActivity{
 -EditText red
 -EditText green
 -EditText blue
 -EditText white
 -void getValues()
 -void setValues(int r, int g, int b, inte w)
}

abstract class DeviceActivity{
 #Device device
 #String macAddress
 #void toggle(boolean)
}


abstract class Device{
 #long id;
 #String macAddress
 +String getMacAddress()
 +long getId()
 +{abstract} String getName()
}

class SensorDevice{
 +String getName()
}

class LightBulb{
 +String getName()
}

class SensorValues {
 -Temperature temperature
 -Pressure pressure
 -Humidity humidity
 -Magnetic magnetic
 -Gyroscopic gyroscopic
 -Accelerometer accelerometer
 +Temperature getTemperature()
 +Pressure getPressure()
 +Humidity getHumidity()
 +Magnetic getMagnetic()
 +Gyroscopic getGyroscopic()
 +Accelerometer getAccelerometer()
}

BaseActivity <|-- MyDevicesActivity
BaseActivity <|-- DeviceActivity
DeviceActivity <|-- SensorDeviceActivity
DeviceActivity <|-- LightBulbActivity

Device <|-- SensorDevice
Device <|-- LightBulb

MyDevicesActivity "1" *-- "1" DeviceListAdapter
DeviceListAdapter "1" o-- "*" Device
BaseActivity "1" o-- "1" NetworkManager
