title Opening application and detecting devices 

actor User
participant MyDevicesActivity
participant NetworkManager

box "Application" #LightBlue
	participant MyDevicesActivity
	participant NetworkManager
end box

database Backend


User -> MyDevicesActivity: Open application
MyDevicesActivity -> NetworkManager: detectDevices(List<Device>, Callback)
NetworkManager -[#0000FF]> Backend : API call
NetworkManager <[#0000FF]- Backend : List<Device> devices
MyDevicesActivity <- NetworkManager : List<Device> devices
MyDevicesActivity -> MyDevicesActivity: Update MyDevicesActivity with \nthe new devices.

