title Turning on a light bulb

participant "LightBulbActivity"
participant NetworkManager

box "Application" #LightBlue
	participant "LightBulbActivity"
	participant NetworkManager
end box

database Backend

LightBulbActivity -> NetworkManager: toggle(Device, Callback)

NetworkManager -[#0000FF]> Backend : API call

NetworkManager <[#0000FF]- Backend : HTTP Response: 200, OK

LightBulbActivity <- NetworkManager : OK

LightBulbActivity -> LightBulbActivity: Update LightBulbActivity\nwith the switch showing\nthat it is on.


