title Getting all sensor data

participant SensorDeviceActivity
participant NetworkManager

box "Application" #LightBlue
	participant SensorDeviceActivity
	participant NetworkManager
end box

database Backend


SensorDeviceActivity -> NetworkManager: getAllSensorValues(Device, Callback)

NetworkManager -[#0000FF]> Backend : API call

NetworkManager <[#0000FF]- Backend : SensorValues

SensorDeviceActivity<- NetworkManager : SensorValues

SensorDeviceActivity-> SensorDeviceActivity: Update SensorDeviceActivity\nwith the new sensor data.


