title Disconnect during interaction with light bulb

participant LightBulbActivity
participant NetworkManager

box "Application" #LightBlue
	participant LightBulbActivity
	participant NetworkManager
end box

database Backend


LightBulbActivity -> NetworkManager: setColor(Device, Color, Callback)

NetworkManager -[#0000FF]> Backend : API call

NetworkManager x<[#0000FF]- Backend : SensorValues

LightBulbActivity<- NetworkManager : Connection lost.

LightBulbActivity-> LightBulbActivity: Display error message.


