package com.etsn05group2.lampcontroller.network.data;

/**
 * Created by Niklas on 2015-09-22.
 * generated by http://timboudreau.com/blog/json/read
 */
public final class DeviceData {
    public final String value;
    public final String time;
    public final String sensorType;
    public final String device;

    public DeviceData(String value, String time, String sensorType, String device){
        this.value = value;
        this.time = time;
        this.sensorType = sensorType;
        this.device = device;
    }
}