package com.etsn05group2.lampcontroller.network;

/**
 * Created by Niklas on 2015-09-21.
 * Generated by http://timboudreau.com/blog/json/read
 */
public final class DeviceData {

    public final long id;
    public final String name;
    public final String deviceAddress;
    public final long status;
    public final String description;
    public final String[] sensors;

    public DeviceData(long id, String name, String deviceAddress, long status, String description, String[] sensors) {
        this.id = id;
        this.name = name;
        this.deviceAddress = deviceAddress;
        this.status = status;
        this.description = description;
        this.sensors = sensors;
    }
}